[application]

# App (Project) Name
name = "lsys-web"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "L-system Playground"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

index_on_404 = false

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `public` in web platform
[web.resource]

# CSS style file

style = ["pico/css/pico.min.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
